# roles/instala_dependencias_linux/vars/main.yaml

apt_upgrade: yes
apt_packages:
  - build-essential
  - curl
  - git
  - libssl-dev
  - zlib1g-dev
  - libpq-dev
  - libicu-dev
  - imagemagick
  - tmux
  - htop
  - acl