---
# roles/start_puma_service/tasks/main.yml
- name: Ensure Puma service file exists
  stat:
    path: "{{ puma_service.service_file }}"
  register: puma_service_file
  become: yes

- name: Fail if Puma service file does not exist
  fail:
    msg: "Puma service file does not exist at {{ puma_service.service_file }}"
  when: not puma_service_file.stat.exists

- name: Reload systemd to recognize new service
  command: systemctl daemon-reload
  when: puma_service_file.stat.exists
  become: yes

- name: Enable Puma service
  systemd:
    name: "{{ puma_service.name }}"
    enabled: yes
  become: yes

- name: Start Puma service
  systemd:
    name: "{{ puma_service.name }}"
    state: started
  become: yes

- name: Wait for Puma to create puma.sock
  wait_for:
    path: "{{ puma_service.socket_path }}"
    state: present
    timeout: "{{ puma_service.socket_timeout }}"
  become: yes
