- name: Clonar repositório DecidimGovBR
  hosts: decidim_server_base
  
  tasks:
    - name: Instalar dependências necessárias
      apt:
        name: git
        state: present
      become: yes
      become_user: root

    - name: Verificar se a pasta /srv/decide existe
      stat:
        path: /srv/decide
      register: decide_folder
      become: yes
      become_user: "{{ regular_user }}"

    - name: Criar a pasta /srv/decide se não existir
      file:
        path: /srv/decide
        state: directory
        owner: "{{ regular_user }}"
        group: "{{ regular_user }}"
        mode: '0775'
      when: not decide_folder.stat.exists
      become: yes
      become_user: root

    - name: Clonar o repositório na tag v1.1.10
      become: yes
      become_user: "{{ regular_user }}"
      git:
        repo: "{{ repo_url }}"
        dest: /srv/decide
        version: "{{ repo_tag }}"
        force: yes
