---
- name: Set default permissions for user 'decide'
  hosts: decidim_server_base
  become: yes
  tasks:
    - name: Set umask for 'decide' user
      lineinfile:
        dest: /home/"{{ regular_user }}"/.bashrc
        line: "umask 002"
        insertafter: EOF
        state: present
        create: yes

    - name: Change owner and group of /srv directory
      file:
        path: /srv
        owner: "{{ regular_user }}"
        group: "{{ regular_user }}"

    - name: Set default ACL for directories created by 'decide'
      acl:
        path: /srv
        entity: decide
        etype: user
        permissions: rwx
        state: present
        default: yes
        recursive: yes

    - name: Set default ACL for files created by 'decide'
      acl:
        path: /srv
        entity: decide
        etype: user
        permissions: rw-
        state: present
        default: yes
        recursive: yes