---
- name: Copy Arquivos de Configuração de Serviços
  hosts: decidim_server_base
  become: yes
  tasks:
    - name: Copia arquivo config do Nginx
      copy:
        src: ../arquivos_ambiente/etc/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf
        mode: 0644

    - name: Copia arquivo config do Decidim dentro do Nginx
      copy:
        src: ../arquivos_ambiente/etc/nginx/conf.d/decide.conf
        dest: /etc/nginx/conf.d/decide.conf
        mode: 0644

    - name: Copia arquivo do Puma
      copy:
        src: ../arquivos_ambiente/etc/systemd/system/decide-puma.service
        dest: /etc/systemd/system/decide-puma.service
        mode: 0644

    - name: Copia arquivo do Sideqik
      copy:
        src: ../arquivos_ambiente/etc/systemd/system/decide-sidekiq.service
        dest: /etc/systemd/system/decide-sidekiq.service
        mode: 0644
