---
- name: Criar usuário decide com permissões de sudo
  hosts: decidim_server_base
  become: yes

  vars:
    user_name: decide
    user_password: "decide"

  tasks:
    - name: Instalar pacote sudo (se necessário)
      apt:
        name: sudo
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Criar usuário decide
      user:
        name: "{{ regular_user }}"
        password: "{{ user_password }}"
        shell: /bin/bash
        create_home: yes

    - name: Adicionar usuário decide ao grupo sudo
      user:
        name: "{{ regular_user }}"
        groups: sudo
        append: yes

    - name: Conceder permissões de sudo sem senha para o usuário decide
      lineinfile:
        dest: /etc/sudoers.d/90-decide
        line: "{{ regular_user }} ALL=(ALL) NOPASSWD:ALL"
        create: yes
        validate: 'visudo -cf %s'

    - name: Ensure decide group exists
      group:
        name: decide
        state: present

    - name: Create nginx user and add to decide group
      user:
        name: nginx
        groups: decide
        append: yes
        state: present

    - name: Create puma-nginx group
      group:
        name: puma-nginx
        state: present

    - name: Add deploy user to puma-nginx group
      user:
        name: decide
        groups: puma-nginx
        append: yes

    - name: Add nginx user to puma-nginx group
      user:
        name: nginx
        groups: puma-nginx
        append: yes
