- hosts: decidim_server_base
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: "{{ apt_upgrade }}"
    - name: Install packages
      apt:
        name: "{{ apt_packages }}"
        state: present