---
- name: Install Nginx on Debian 12
  hosts: decidim_server_base
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is enabled and started
      service:
        name: nginx
        state: started
        enabled: yes
