- hosts: decidim_server_base
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Install packages
      apt:
        name:
          - build-essential
          - curl
          - git
          - libssl-dev
          - zlib1g-dev
          - libpq-dev
          - libicu-dev
          - imagemagick
          - tmux
          - htop
          - acl
        state: present