---
- name: Install and configure Ruby 3.0.4 using rbenv
  hosts: decidim_server_base

  tasks:
    - name: Ensure necessary dependencies are installed
      apt:
        name: "{{ ruby_pre_requisites }}"
        state: present
      become: yes
      become_user: root

    - name: Clone rbenv repository
      git:
        repo:  "{{ rbenv_repo_url }}"
        # dest: "{{ ansible_env.HOME }}/.rbenv"
        dest: "/home/{{ regular_user }}/.rbenv"
        version: 'master'
        update: no
      become: yes
      become_user: "{{ regular_user }}"

    - name: Clone ruby-build repository
      git:
        repo: "{{ ruby_build_repo_url }}"
        # dest: "{{ ansible_env.HOME }}/.rbenv/plugins/ruby-build"
        dest: "/home/{{ regular_user }}/.rbenv/plugins/ruby-build"
        version: 'master'
        update: no
      become: yes
      become_user: "{{ regular_user }}"

    - name: Add rbenv to PATH
      shell: 'echo ''export PATH="/home/{{ regular_user }}/.rbenv/bin:$PATH"'' >> /home/{{ regular_user }}/.bashrc'
      # shell: 'echo ''export PATH="{{ ansible_env.HOME }}/.rbenv/bin:$PATH"'' >> {{ ansible_env.HOME }}/.bashrc'
      args:
        executable: /bin/bash
      become: yes
      become_user: root

    - name: Add rbenv init to bashrc
      # shell: 'echo ''eval "$(rbenv init -)"'' >> {{ ansible_env.HOME }}/.bashrc'
      shell: 'echo ''eval "$(rbenv init -)"'' >> /home/{{ regular_user }}/.bashrc'
      args:
        executable: /bin/bash
      become: yes
      become_user: "{{ regular_user }}"

    - name: Source .bashrc
      shell: source ~/.bashrc
      args:
        executable: /bin/bash
      become: yes
      become_user: "{{ regular_user }}"

    - name: List all installed Ruby versions
      shell: "/home/{{ regular_user }}/.rbenv/bin/rbenv versions --bare"
      args:
        executable: /bin/bash
      register: ruby_versions
      become: yes
      become_user: "{{ regular_user }}"

    - name: Print installed Ruby versions
      debug:
        msg: "Installed Ruby versions: {{ ruby_versions.stdout_lines }}"

    - name: Check if Ruby 3.0.4 is already installed
      become: yes
      shell: "/home/{{ regular_user }}/.rbenv/bin/rbenv versions --bare | grep -w 3.0.4"
      args:
        executable: /bin/bash
      register: ruby_check
      ignore_errors: true
      become: yes
      become_user: "{{ regular_user }}"

    - name: Install Ruby 3.0.4 using rbenv
      # shell: "{{ ansible_env.HOME }}/.rbenv/bin/rbenv install 3.0.4"
      shell: "/home/{{ regular_user }}/.rbenv/bin/rbenv install 3.0.4"
      args:
        executable: /bin/bash
      environment:
        # RBENV_ROOT: "{{ ansible_env.HOME }}/.rbenv"
        RBENV_ROOT: "/home/{{ regular_user }}/.rbenv"
      become: yes
      become_user: "{{ regular_user }}"
      when: ruby_check.rc != 0 

    - name: Set Ruby 3.0.4 as global version using rbenv
      # shell: "{{ ansible_env.HOME }}/.rbenv/bin/rbenv global 3.0.4"
      shell: "/home/{{ regular_user }}/.rbenv/bin/rbenv global 3.0.4"
      args:
        executable: /bin/bash
      environment:
        # RBENV_ROOT: "{{ ansible_env.HOME }}/.rbenv"
        RBENV_ROOT: "/home/{{ regular_user }}/.rbenv"
      become: yes
      become_user: "{{ regular_user }}"

    - name: Install Bundler
      shell: |
        export PATH="/home/{{ regular_user }}/.rbenv/bin:$PATH"
        eval "$(rbenv init -)"
        gem install bundler -v '~> 2.2.33'
      become: yes
      become_user: "{{ regular_user }}"
