---
- name: Install Node.js 16 on Linux
  hosts: decidim_server_base
  become: true  # Requires elevated privileges
  tasks:
    # Install prerequisites using apt
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install curl
      apt:
        name: "{{ curl_package_name }}"
        state: present

    - name: Download NodeSource installation script (on remote host)
      shell: curl -sL {{ node_setup_url }} | bash -

    # Update apt cache again
    - name: Update apt cache after adding repository
      apt:
        update_cache: yes

    # Install Node.js
    - name: Install Node.js 16
      apt:
        name: "{{ nodejs_package_name }}"
        state: present