---
- name: Sobe Containers Redis e Postgres
  hosts: decidim_server_base
  become: yes
  tasks:
    - name: Run Docker Compose
      command: docker compose -f docker-compose-backstage.yml up -d
      args:
        chdir: /srv/decide