---
- name: Enable and start Puma service
  hosts: decidim_server_base
  become: yes
  tasks:
    - name: Ensure Puma service file exists
      stat:
        path: /etc/systemd/system/{{ puma_service_name }}.service
      register: puma_service_file

    - name: Fail if Puma service file does not exist
      fail:
        msg: "Puma service file does not exist at /etc/systemd/system/{{ puma_service_name }}.service"
      when: not puma_service_file.stat.exists

    - name: Reload systemd to recognize new service
      command: systemctl daemon-reload
      when: puma_service_file.stat.exists

    - name: Enable Puma service
      systemd:
        name: "{{ puma_service_name }}"
        enabled: yes

    - name: Start Puma service
      systemd:
        name: "{{ puma_service_name }}"
        state: started