---
- name: Reload systemd services and restart Nginx
  hosts: decidim_server_base
  become: yes
  tasks:
    - name: Change ownership and permissions of puma.sock
      file:
        path: /srv/decide/tmp/sockets/puma.sock
        owner: nginx
        group: "{{ regular_user }}"
        mode: '0777'

    - name: Reload systemd manager configuration
      command: systemctl daemon-reload

    - name: Restart Nginx service
      systemd:
        name: nginx
        state: restarted
